language: python

python:
  - "2.7"
  
# command to install dependencies
install: "pip install pylint"

# command to run tests
script: "pylint addnumber.py"

after_success:
  - "curl -o travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
  - "chmod a+x travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^d' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=KL-Hu/TravisTest travis-automerge"